version: 2.1

setup: true

orbs: 
  # continuation: circleci/continuation@0.2.0
  path: circleci/path-filtering@0.1.3

workflows:
  setup:
    jobs:
      - path/filter:
          config-path: .circleci/next.yml
          mapping: |
            repo-a/.* repo_a true
            repo-b/.* repo_b true
            repo-c/.* repo_c true
            .circleci/.* repo_a true
            .circleci/.* repo_b true
            .circleci/.* repo_c true
