version: 2.1

setup: true

jobs:
  exit-early:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Exit early if only config changed
          command: |
            # list files changed since previous commit
            git diff --name-only HEAD~1 HEAD > changed.txt
            
            if [ $(wc -l < changed.txt) -eq 1 ] && [ $(head -n 1 changed.txt) = ".circleci/config.yml" ]; then
               curl --request POST \
                 --url "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/cancel" \
                 --header "Circle-Token: ${CIRCLE_TOKEN}"
            fi
      - run:
          name: test
          command: |
            echo "this is run only if the workflow is not cancelled"
            

workflows:
  setup:
    jobs:
      - exit-early
