version: 2.1

parameters:
  continue:
    type: boolean
    default: false
  build-code:
    type: boolean
    default: false

executors:
  base:
    docker:
      - image: cimg/base:stable
    resource_class: small

jobs:
  done:
    executor: base
    steps:
      - run: echo "DONE"
  build:
    executor: base
    steps:
      - checkout
      - run: cat src/bar.py

workflows:
  no-op:
    when:
      and:
        - not: << pipeline.parameters.build-code >>
        - << pipeline.parameters.continue >>
    jobs:
      - done
  build-code:
    when:
      and:
        - << pipeline.parameters.build-code >>
        - << pipeline.parameters.continue >>
    jobs:
      - build
      - done:
          requires:
            - build
