version: 2.1

parameters:
  build-repo-a:
    type: boolean
    default: false
  build-repo-b:
    type: boolean
    default: false

executors:
  base:
    docker:
      - image: cimg/base:stable
    resource_class: small

jobs:
  done:
    executor: base
    steps:
      - run: echo "DONE"
  build:
    parameters:
      workdir:
        type: string
    executor: base
    working_directory: << parameters.workdir >>
    steps:
      - checkout:
          path: ~/project
      - run: |
          ls -laH .

workflows:
  no-op:
    when:
      and:
        - not: << pipeline.parameters.build-repo-a >>
        - not: << pipeline.parameters.build-repo-b >>
    jobs:
      - done
  repo-a:
    when: << pipeline.parameters.build-repo-a >>
    jobs:
      - build:
          workdir: repo-a
      - done:
          requires:
            - build
  repo-b:
    when: << pipeline.parameters.build-repo-b >>
    jobs:
      - build:
          workdir: repo-a
      - done:
          requires:
            - build
