version: 2.1

parameters:
  repo_a:
    type: boolean
    default: false
  repo_b:
    type: boolean
    default: false
  repo_c:
    type: boolean
    default: false

executors:
  base:
    docker:
      - image: cimg/base:stable
    resource_class: small

commands:
  exit-early-if-irrelevant:
    parameters:
      for:
        description: which repo this job is relevant for
        type: enum
        enum:
          - repo_a
          - repo_b
          - repo_c
    steps:
      - run:
          name: stop early unless relevant
          command: |
            # looks up the relevant pipeline parameter via the env var
            export RELEVANT=$(eval echo "\$<< parameters.for >>")

            # NOTE: env var values are strings (not boolean)
            if [ "${RELEVANT}" = "1" ]; then
              echo "continuing, since job is for << parameters.for >>"
            else
              echo "stopping early!"
              circleci-agent step halt
            fi
          environment:
            repo_a: << pipeline.parameters.repo_a >>
            repo_b: << pipeline.parameters.repo_b >>
            repo_c: << pipeline.parameters.repo_c >>

jobs:
  test_repo_a:
    executor: base
    steps:
      # exit early IF pipeline.parameters.repo_a is FALSE
      - unless:
          condition: << pipeline.parameters.repo_a >>
          steps:
            - run: |
                circleci-agent step halt
      - checkout
      - run: echo "TODO test repo_a"
  test:
    parameters:
      for:
        type: enum
        enum:
          - repo_a
          - repo_b
          - repo_c
    executor: base
    steps:
      - exit-early-if-irrelevant:
          for: << parameters.for >>
      - checkout
      - run: |
          sleep 5
          echo "TODO test << parameters.for >>"
  deploy:
    parameters:
      for:
        type: enum
        enum:
          - repo_a
          - repo_b
          - repo_c
    executor: base
    steps:
      - exit-early-if-irrelevant:
          for: << parameters.for >>
      - checkout
      - run: |
          sleep 5
          echo "DONE deploy << parameters.for >>"

workflows:
  repo_a:
    jobs:
      - test_repo_a

  repo_b:
    jobs:
      - test:
          for: repo_b
          name: test_repo_b
      - deploy:
          for: repo_b
          name: deploy_repo_b
          requires:
            - test_repo_b
  repo_c:
    jobs:
      - test:
          for: repo_c
          name: test_repo_c
      - deploy:
          for: repo_c
          name: deploy_repo_c
          requires:
            - test_repo_c
