version: 2.1

parameters:
  build-repo-a:
    type: boolean
    default: false
  build-repo-b:
    type: boolean
    default: false

executors:
  base:
    docker:
      - image: cimg/base:stable
    resource_class: small

jobs:
  done:
    executor: base
    steps:
      - run: echo "DONE"
  build-repo-a:
    executor: base
    working_directory: ~/project/repo-a
    steps:
      - unless:
          condition: << pipeline.parameters.build-repo-a >>
          steps:
            - run: |
                circleci-agent step halt
      - checkout:
          path: ~/project
      - run: |
          ls -laH .
  build-repo-b:
    executor: base
    working_directory: ~/project/repo-b
    steps:
      - unless:
          condition: << pipeline.parameters.build-repo-b >>
          steps:
            - run: |
                circleci-agent step halt
      - checkout:
          path: ~/project
      - run: |
          ls -laH .

workflows:
  just-this-one:
    jobs:
      - build-repo-a
      - build-repo-b
      - done:
          requires:
            - build-repo-a
            - build-repo-b
